#���p�҃e�[�u��
CREATE TABLE USER_TABLE (
  USER_ID           INT(9)          NOT NULL PRIMARY KEY    COMMENT '���p��ID',
  USER_NAME         VARCHAR(100)    NOT NULL                COMMENT '���p�Җ�'                 
);
INSERT INTO USER_TABLE (USER_ID , USER_NAME)
VALUES (1, 'OI') ;
INSERT INTO USER_TABLE (USER_ID , USER_NAME)
VALUES (2, 'KAWAKITA') ;
INSERT INTO USER_TABLE (USER_ID , USER_NAME)
VALUES (3, 'SANO') ;
INSERT INTO USER_TABLE (USER_ID , USER_NAME)
VALUES (4, 'HAYASHI') ;
INSERT INTO USER_TABLE (USER_ID , USER_NAME)
VALUES (5, 'MAMIYA') ;

#�{�e�[�u��
CREATE TABLE BOOK_TABLE (
  BOOK_ID           INT(9)          NOT NULL PRIMARY KEY    COMMENT '�{ID',
  BOOK_TITLE         VARCHAR(100)    NOT NULL                COMMENT '�{�̃^�C�g��'                 
);
INSERT INTO BOOK_TABLE (BOOK_ID, BOOK_TITLE)
VALUES (1, '�����s�[�X') ;
INSERT INTO BOOK_TABLE (BOOK_ID, BOOK_TITLE)
VALUES (2, '�X�p�C�t�@�~���[') ;
INSERT INTO BOOK_TABLE (BOOK_ID, BOOK_TITLE)
VALUES (3, '�n���[�|�b�^�[�ƌ��҂̐�') ;
INSERT INTO BOOK_TABLE (BOOK_ID, BOOK_TITLE)
VALUES (4, 'Java����') ;
INSERT INTO BOOK_TABLE (BOOK_ID, BOOK_TITLE)
VALUES (5, 'springboot�Q�l��') ;


#�{�Ǘ��󋵃e�[�u��
CREATE TABLE BOOK_PLAN_TABLE (
  USER_ID           INT(9)           NOT NULL    COMMENT '���p��ID',
  BOOK_ID           INT(9)           NOT NULL    COMMENT '�{ID',
  READ_FLAG         INT(1)           DEFAULT 0   COMMENT '���ǃt���O',
  DELETE_FLAG       INT(1)           DEFAULT 0   COMMENT '�폜�t���O'
  PRIMARY KEY(USER_ID, BOOK_ID)                 
);

#�e�X�g�f�[�^
INSERT INTO BOOK_PLAN_TABLE (USER_ID, BOOK_ID, READ_FLAG)
VALUES (1, 1, 0) ;
INSERT INTO BOOK_PLAN_TABLE (USER_ID, BOOK_ID, READ_FLAG)
VALUES (1, 2, 0) ;
INSERT INTO BOOK_PLAN_TABLE (USER_ID, BOOK_ID, READ_FLAG)
VALUES (2, 1, 1) ;
INSERT INTO BOOK_PLAN_TABLE (USER_ID, BOOK_ID, READ_FLAG)
VALUES (2, 2, 0) ;
INSERT INTO BOOK_PLAN_TABLE (USER_ID, BOOK_ID, READ_FLAG)
VALUES (2, 4, 0) ;
INSERT INTO BOOK_PLAN_TABLE (USER_ID, BOOK_ID, READ_FLAG)
VALUES (3, 1, 0) ;
                

#�ǂ݂����{�̒ǉ�
INSERT INTO BOOK_PLAN_TABLE (USER_ID, BOOK_ID)
VALUES (1, 4) ;



#�ǂ݂����{�̈ꗗ
SELECT a.USER_NAME , c.BOOK_TITLE
  FROM (USER_TABLE a INNER JOIN BOOK_PLAN_TABLE b ON b.USER_ID = a.USER_ID)
                     INNER JOIN BOOK_TABLE c ON b.BOOK_ID = c.BOOK_ID 
  WHERE b.USER_ID = 1
  AND b.READ_FLAG = 0
  AND b.DELETE_FLAG = 0
 ORDER BY b.BOOK_ID ;
 
 
#���ǂ����{�̈ꗗ
SELECT a.USER_NAME , c.BOOK_TITLE
  FROM (USER_TABLE a INNER JOIN BOOK_PLAN_TABLE b ON b.USER_ID = a.USER_ID)
                     INNER JOIN BOOK_TABLE c ON b.BOOK_ID = c.BOOK_ID 
  WHERE b.USER_ID = 2
  AND b.READ_FLAG = 1
  AND b.DELETE_FLAG = 0
 ORDER BY b.BOOK_ID ;
  
 

#�ǂ݂����{�̕ҏW
UPDATE BOOK_TABLE
SET c.BOOK_TITLE = '�ύX��̃^�C�g��'
FROM (USER_TABLE a INNER JOIN BOOK_PLAN_TABLE b ON b.USER_ID = a.USER_ID)
                     INNER JOIN BOOK_TABLE c ON b.BOOK_ID = c.BOOK_ID 
WHERE USER_ID = 1
  AND BOOK_ID = 1 ;
ORDER BY b.BOOK_ID ;
  
  
#�ǂ݂����{�̍폜
UPDATE BOOK_PLAN_TABLE
SET READ_FLAG = 1
WHERE USER_ID = 1
  AND BOOK_ID = 2
  AND READ_FLAG = 0 ;


#�ǂ݂����{�̊���
UPDATE BOOK_PLAN_TABLE
SET READ_FLAG = 1
WHERE USER_ID = 1
  AND BOOK_ID = 2
  AND READ_FLAG = 0 ;
  
  
#�ǂ񂾖{�𖢓ǂ�
UPDATE BOOK_PLAN_TABLE
SET READ_FLAG = 0
WHERE USER_ID = 1
  AND BOOK_ID = 2
  AND READ_FLAG = 1 ;


